distributed:
  backend: null  # null -> nccl on GPU, gloo on CPU
  gradient_accumulation_steps: 1
amp: no  # no | fp16 | bf16
ddp:
  find_unused_parameters: False
train_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.TabularDataset
    path: /home/datalab/nfs/avatar_fm/examples/tabular_hidden_states/data/td_processed/train
    shuffle_files: True
    shuffle_pq: True
    hidden_state_column: seq_hidden_state # название колонки с hidden_state
  batch_size: 2048
  pin_memory: True
  drop_last: False
  num_workers: 8
  collate_fn:
    _target_: avatar.data.TabularCollateFn
    target_column: target_attr_1
valid_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.TabularDataset
    path: /home/datalab/nfs/avatar_fm/examples/tabular_hidden_states/data/td_processed/valid
    shuffle_files: False
    shuffle_pq: False
    hidden_state_column: seq_hidden_state # название колонки с hidden_state
  batch_size: 2048
  pin_memory: True
  drop_last: False
  num_workers: 8
  collate_fn:
    _target_: avatar.data.TabularCollateFn
    target_column: target_attr_1
model:
  _target_: avatar.pipeline.tabular.TabularClassification
  tabular_model:
    _target_: avatar.pipeline.tabular.TabularWithAggregatedStates
    embedding:
      _target_: avatar.nn.embedding.TabularEmbedding
      num_numerical_features: 189
      hidden_size: 64
      vocab_size: 172
      std_noise: null
      hidden_state_aggregator:
        _target_: avatar.nn.embedding.LayerNormConcatenate
        hidden_state_dim: 128 # Размерность external hidden_state
        embedding_dim: ${model.tabular_model.embedding.hidden_size} # Размерность на выходе из Tabular Embedding
    encoder:
      _target_: avatar.nn.tabular.TabularTransformer
      hidden_size: ${model.tabular_model.embedding.hidden_size}
      num_heads: 4
      num_layers: 3
      attn_dropout: 0.15
    aggregation_config:
      name: linear
      num_features: 244 # 243 табличных фичи на входе 
      emb_dim: ${model.tabular_model.embedding.hidden_size}
    late_fusion_hidden_state_dim: 128 # Размерность hidden_state
  num_classes: 2
  dropout_p: 0.15
  task_type: classification
mlflow:
  experiment_name: tabular_hidden_states
  run_name: late_early_fusion
  logging_dir: /home/datalab/nfs/mlruns
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.001
  weight_decay: 0
  scale_lr_multigpu: True
scheduler:
  _target_: transformers.optimization.get_scheduler
  _partial_: True
  name: cosine
  num_warmup_steps: 1000
  num_training_steps: 300_000
train:
  start_epoch: 0
  checkpoint_state: null
  model_state: null
  seed: 42
  num_epochs: 50
  clip_grad_norm: null
  max_saved_checkpoints: 5
  device_specific: True
  early_stopping:
    _target_: avatar.train.EarlyStopping
    main_metric: roc_auc_score
    patience: 6
    delta: 0
    strategy: max
metrics:
  valid_metrics:
    _target_: avatar.metrics.RocAucScore
