accelerator:
  _target_: accelerate.Accelerator
  _partial_: True
  dataloader_config:
    _target_: accelerate.utils.DataLoaderConfiguration
    dispatch_batches: False
train_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.dataset.TabularDataset
    path: /home/datalab/nfs/avatar_fm/examples/tabular_hidden_states/data/td_processed/train
    shuffle_files: True
    shuffle_pq: True
  batch_size: 2048
  pin_memory: True
  drop_last: False
  num_workers: 8
  collate_fn:
    _target_: avatar.data.dataset.collate_fn.TabularCollateFn
    target_column: target_attr_1
valid_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.dataset.TabularDataset
    path: /home/datalab/nfs/avatar_fm/examples/tabular_hidden_states/data/td_processed/valid
    shuffle_files: False
    shuffle_pq: False
  batch_size: 2048
  pin_memory: True
  drop_last: False
  num_workers: 8
  collate_fn:
    _target_: avatar.data.dataset.collate_fn.TabularCollateFn
    target_column: target_attr_1
model:
  _target_: avatar.pipeline.tabular.TabularClassification
  tabular_model:
    _target_: avatar.pipeline.tabular.TabularWithAggregatedStates
    backbone:
      _target_: avatar.nn.tabular.STEv2
      embedding:
        _target_: avatar.nn.embedding.TabularEmbedding
        num_numerical_features: 189
        hidden_size: 64
        vocab_size: 172
        std_noise: null
      num_heads: 4
      num_layers: 3
      attn_dropout: 0.15
    aggregation_config:
      name: linear
      num_features: 243 # Размер hidden_state на выходе из STEv2, у нас всего 243 табличных фичи на входе поэтому num_features 243 
      emb_dim: ${model.tabular_model.backbone.embedding.hidden_size}
  num_classes: 2
  dropout_p: 0.15
  task_type: classification
mlflow:
  experiment_name: tabular_hidden_states
  run_name: tabular_baseline
  logging_dir: /home/datalab/nfs/mlruns
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.001
  weight_decay: 0
  scale_lr_multigpu: True
scheduler:
  _target_: transformers.optimization.get_scheduler
  _partial_: True
  name: cosine
  num_warmup_steps: 1000
  num_training_steps: 300_000
train:
  start_epoch: 0
  checkpoint_state: null
  model_state: null
  seed: 42
  num_epochs: 50
  clip_grad_norm: null
  max_saved_checkpoints: 5
  device_specific: True
  early_stopping:
    _target_: avatar.train_utils.EarlyStopping
    main_metric: roc_auc_score
    patience: 6
    delta: 0
    strategy: max
metrics:
  valid_metrics:
    _target_: avatar.metrics.RocAucScore