distributed:
  backend: null  # null -> nccl on GPU, gloo on CPU
  gradient_accumulation_steps: 2
amp: no  # no | fp16 | bf16
ddp:
  find_unused_parameters: True
train_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.EventSequenceDataset
    path: /home/datalab/projects/avatards/moshcharov/parquet_for_test_downstream/train_debug
    min_length: 16
    max_length: 512
    random_slicing: True
    event_time_column: "evt_dttm"
    event_ids_column: "event_ids"
    sequence_columns: ['txn_evt_attr_9', 'txn_evt_attr_4', 'txn_evt_attr_5', 'txn_evt_attr_1', 'txn_evt_attr_2', 'txn_evt_attr_3', 'evk_vnv_evt_attr_1', 'evk_vnv_channel_group', 'evk_vnv_sale_product_class_id', 'evk_vnv_sale_type_id', 'pos_geo_evt_attr_1', 'txn_evt_attr_15']
    read_columns: ['event_ids', 'evt_dttm', 'txn_evt_attr_9', 'txn_evt_attr_4', 'txn_evt_attr_5', 'txn_evt_attr_1', 'txn_evt_attr_2', 'txn_evt_attr_3', 'evk_vnv_evt_attr_1', 'evk_vnv_channel_group', 'evk_vnv_sale_product_class_id', 'evk_vnv_sale_type_id', 'pos_geo_evt_attr_1', 'txn_evt_attr_15']
    selected_event_ids: [0, 1, 2]
    shuffle_files: True
    shuffle_pq: True
  batch_size: 5
  pin_memory: True
  drop_last: True
  num_workers: 8
  collate_fn:
    _target_: avatar.data.EventSequenceCollateFn
    sequence_columns: ${train_dataloader.dataset.sequence_columns}
    create_attention_mask: True
valid_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.EventSequenceDataset
    path: /home/datalab/projects/avatards/moshcharov/parquet_for_test_downstream/train_debug
    max_length: 512
    event_time_column: "evt_dttm"
    event_ids_column: "event_ids"
    sequence_columns: ['txn_evt_attr_9', 'txn_evt_attr_4', 'txn_evt_attr_5', 'txn_evt_attr_1', 'txn_evt_attr_2', 'txn_evt_attr_3', 'evk_vnv_evt_attr_1', 'evk_vnv_channel_group', 'evk_vnv_sale_product_class_id', 'evk_vnv_sale_type_id', 'pos_geo_evt_attr_1', 'txn_evt_attr_15']
    read_columns: ['event_ids', 'evt_dttm', 'txn_evt_attr_9', 'txn_evt_attr_4', 'txn_evt_attr_5', 'txn_evt_attr_1', 'txn_evt_attr_2', 'txn_evt_attr_3', 'evk_vnv_evt_attr_1', 'evk_vnv_channel_group', 'evk_vnv_sale_product_class_id', 'evk_vnv_sale_type_id', 'pos_geo_evt_attr_1', 'txn_evt_attr_15']
    selected_event_ids: [0, 1, 2]
    shuffle_files: False
    shuffle_pq: False
  batch_size: 5
  pin_memory: True
  drop_last: False
  num_workers: 8
  collate_fn:
    _target_: avatar.data.EventSequenceCollateFn
    sequence_columns: ${valid_dataloader.dataset.sequence_columns}
    create_attention_mask: True
test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.EventSequenceDataset
    path: /home/datalab/projects/avatards/moshcharov/parquet_for_test_downstream/test
    max_length: 512
    event_time_column: "evt_dttm"
    event_ids_column: "event_ids"
    sequence_columns: ['txn_evt_attr_9', 'txn_evt_attr_4', 'txn_evt_attr_5', 'txn_evt_attr_1', 'txn_evt_attr_2', 'txn_evt_attr_3', 'evk_vnv_evt_attr_1', 'evk_vnv_channel_group', 'evk_vnv_sale_product_class_id', 'evk_vnv_sale_type_id', 'pos_geo_evt_attr_1', 'txn_evt_attr_15']
    read_columns: ['epk_id', 'target_attr_1', 'target_attr_2', 'target_attr_3', 'report_month', 'product_name', 'event_ids', 'evt_dttm', 'txn_evt_attr_9', 'txn_evt_attr_4', 'txn_evt_attr_5', 'txn_evt_attr_1', 'txn_evt_attr_2', 'txn_evt_attr_3', 'evk_vnv_evt_attr_1', 'evk_vnv_channel_group', 'evk_vnv_sale_product_class_id', 'evk_vnv_sale_type_id', 'pos_geo_evt_attr_1', 'txn_evt_attr_15']
    selected_event_ids: [0, 1, 2]
    shuffle_files: False
    shuffle_pq: False
  batch_size: 5
  pin_memory: True
  drop_last: False
  num_workers: 8
  collate_fn:
    _target_: avatar.data.EventSequenceCollateFn
    sequence_columns: ${test_dataloader.dataset.sequence_columns}
    create_attention_mask: True
    target_column: 'target_attr_1'
    
    
model:
  _target_: avatar.pipeline.sequence.NextKTokensPrediction
  aggregation_config:
    name: sum
  model:
    _target_: avatar.nn.sequential.TransformersWrapper
    event_encoder:
      _target_: avatar.nn.sequential.EventEncoder
      dropout_p: 0.1
      time_encoding: delta
      embedding:
        _target_: avatar.nn.embedding.EventSequenceEmbedding
        hidden_size: 128
        columns_meta:
          txn_evt_attr_9:
            type: categorical
            n_classes: 684
            event_id: [0, 1]
            clip: 175
          txn_evt_attr_4:
            type: categorical
            n_classes: 3
            event_id: [0, 1]
          txn_evt_attr_5:
            type: categorical
            n_classes: 3
            event_id: [0, 1]
          txn_evt_attr_1:
            type: categorical
            n_classes: 429
            event_id: 0
            clip: 64
          txn_evt_attr_2:
            type: categorical
            n_classes: 4
            event_id: 0
          txn_evt_attr_3:
            type: categorical
            n_classes: 44
            event_id: 0
            clip: 21
          evk_vnv_evt_attr_1:
            type: categorical
            n_classes: 3
            event_id: 2
          evk_vnv_channel_group:
            type: categorical
            n_classes: 10
            event_id: 2
            clip: 7
          evk_vnv_sale_product_class_id:
            type: categorical
            n_classes: 37
            event_id: 2
            clip: 28
          evk_vnv_sale_type_id:
            type: categorical
            n_classes: 22
            event_id: 2
            clip: 18
          pos_geo_evt_attr_1:
            type: categorical
            n_classes: 87
            event_id: null
            clip: 84
          txn_evt_attr_15:
            type: numeric
            n_classes: 1
            event_id: [0, 1]
            clip: 3
    backbone:
      _target_: transformers.GPT2Model
      config:
        _target_: transformers.GPT2Config
        n_positions: 512
        vocab_size: 0 # может быть любое значение, так как nn.Embedding gpt мы не используем
        n_embd: ${model.model.event_encoder.embedding.hidden_size}
        n_layer: 6
        n_head: 4
        pad_token_id: 0
        bos_token_id: 1
        eos_token_id: 2
mlflow:
  experiment_name: debug
  run_name: debug
  logging_dir: ./mlruns
  
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.001
  weight_decay: 0.01
  scale_lr_multigpu: False
  
scheduler:
  _target_: transformers.optimization.get_scheduler
  _partial_: True
  name: cosine
  num_warmup_steps: 6000
  num_training_steps: null
  
train:
  start_epoch: 0
  checkpoint_state: null
  model_state: null
  seed: 42
  num_epochs: 1
  clip_grad_norm: 1.5
  max_saved_checkpoints: null
  device_specific: False
  early_stopping: null
  


metrics:
  valid_metrics:
    _target_: avatar.metrics.MultiLossMetric
  test_metrics:
    _target_: avatar.metrics.MLPCampaignBenchmark
    path_to_save: /home/datalab/nfs/avatar_fm/experiments/moshcharov/data/final_D_E_B_U_G
    save_steps: 100
    path_to_config_dir: /home/datalab/nfs/avatar_fm/experiments/moshcharov/configs
    config_name: mlp_bench.yaml
    mlflow_run_name: f_i_n_a_l
    mlflow_exp_name: debug
    contour_name_column: "product_name"
    additional_columns: ["target_attr_1", "target_attr_2", "target_attr_3"]
    
    split: 
      train: '2024-09-30'
      valid: '2024-10-31'
      test: '2024-12-31'
    compute_contour: ['cc_response', 'sa_response', 'pl_response', 'td_response']