PATH_TO_SAVE_PREDICT: /home/datalab/nfs/avatar_fm/experiments/moshcharov/data/debug_cat_feature_mlpbench_rest/debug_mlp_bench_cat_feat_rest_debug/cc_response/predict
accelerator:
  _target_: accelerate.Accelerator
  _partial_: True
  dataloader_config:
    _target_: accelerate.utils.DataLoaderConfiguration
    dispatch_batches: False
  
train_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.TabularDataset
    path: /home/datalab/nfs/avatar_fm/experiments/moshcharov/data/debug_cat_feature_mlpbench/debug_mlp_bench_cat_feat_debug/cc_response/train
    read_columns: ["seq_hidden_state", "target_attr_1", "target_attr_2", "target_attr_3", "epk_id", 'cat_features']
    shuffle_files: True
    shuffle_pq: True
    hidden_state_column: "seq_hidden_state"
  batch_size: 4096
  pin_memory: True
  drop_last: True
  num_workers: 8
  collate_fn:
    _target_: avatar.data.TabularCollateFn
    target_column: "target_attr_1"
    
valid_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.TabularDataset
    path:  /home/datalab/nfs/avatar_fm/experiments/moshcharov/data/debug_cat_feature_mlpbench/debug_mlp_bench_cat_feat_debug/cc_response/valid
    read_columns: ["seq_hidden_state", "target_attr_1", "target_attr_2", "target_attr_3", "epk_id", 'cat_features']
    shuffle_files: false
    shuffle_pq: false
    hidden_state_column: "seq_hidden_state"
  batch_size: 4096
  pin_memory: True
  drop_last: False
  num_workers: 8
  collate_fn:
    _target_: avatar.data.TabularCollateFn
    target_column: "target_attr_1"
    
test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: avatar.data.TabularDataset
    path:  /home/datalab/nfs/avatar_fm/experiments/moshcharov/data/debug_cat_feature_mlpbench/debug_mlp_bench_cat_feat_debug/cc_response/test
    read_columns: ["seq_hidden_state", "target_attr_1", "target_attr_2", "target_attr_3", "epk_id", 'cat_features']
    shuffle_files: false
    shuffle_pq: false
    hidden_state_column: "seq_hidden_state"
  batch_size: 4096
  pin_memory: True
  drop_last: false
  num_workers: 8
  collate_fn:
    _target_: avatar.data.TabularCollateFn
    target_column: "target_attr_1"    


model:
  _target_: avatar.pipeline.tabular.TabularClassification
  tabular_model:
    _target_: avatar.nn.tabular.MLPEmbedding
    embedding_dim_attr_2: 4
    embedding_dim_attr_3: 2
  num_classes: 2
  dropout_p: 0.15
  task_type: "classification"
  extra_hidden_dim: 128
  out_head_hidden_dim: 512
  hidden_proj_dim: null
  output_head: null
  
mlflow:
  experiment_name: rest_tar_2_tar_3
  run_name: debug
  logging_dir: ./mlruns
  
optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.0007
  weight_decay: 0.01
  scale_lr_multigpu: True
  eps: 1e-4
  
scheduler:
  _target_: transformers.optimization.get_scheduler
  _partial_: True
  name: cosine
  num_warmup_steps: 6000
  
train:
  start_epoch: 0
  checkpoint_state: null
  model_state: null
  seed: 42
  num_epochs: 50
  clip_grad_norm: 1.5
  max_saved_checkpoints: 15
  device_specific: False
  early_stopping:
    _target_: avatar.train_utils.EarlyStopping
    main_metric: avg_calib_roc_auc_score
    patience: 15
    delta: 0.0001
    strategy: max



metrics:
  valid_metrics:
  - _target_: avatar.metrics.utils.GroupAverageMetricWrapper
    metric:
      _target_: avatar.metrics.utils.GroupAverageMetricWrapper
      metric:
        _target_: avatar.metrics.utils.GroupDevidedMetricsWrapper
        columns_to_devide: ['target_attr_2', 'target_attr_3']
        columns_desc: ['channel', 'group']
        metric_class:
          _target_: avatar.metrics.RocAucScore
          _partial_: true # set true !!!

      avg_over_regulars:
        # calib
        avg_calib_control_group_roc_auc_score: ^channel_\d+_group_1_roc_auc_score
        avg_calib_target_group_roc_auc_score: ^channel_\d+_group_0_roc_auc_score

        avg_calib_channel_0_roc_auc_score: ^channel_0_group_\d+_roc_auc_score
        avg_calib_channel_1_roc_auc_score: ^channel_1_group_\d+_roc_auc_score
        avg_calib_channel_2_roc_auc_score: ^channel_2_group_\d+_roc_auc_score
        avg_calib_channel_3_roc_auc_score: ^channel_3_group_\d+_roc_auc_score

  
    groups: 
      avg_calib_roc_auc_score: ['avg_calib_control_group_roc_auc_score' , 'avg_calib_target_group_roc_auc_score']
    
    
  test_metrics:
  - _target_: avatar.metrics.utils.GroupAverageMetricWrapper
    metric:
      _target_: avatar.metrics.utils.GroupAverageMetricWrapper
      metric:
        _target_: avatar.metrics.utils.GroupDevidedMetricsWrapper
        columns_to_devide: ['target_attr_2', 'target_attr_3']
        columns_desc: ['channel', 'group']
        metric_class:
          _target_: avatar.metrics.RocAucScore
          _partial_: true # set true !!!

      avg_over_regulars:
        # calib
        avg_test_control_group_roc_auc_score: ^channel_\d+_group_1_roc_auc_score
        avg_test_target_group_roc_auc_score: ^channel_\d+_group_0_roc_auc_score

        avg_test_channel_0_roc_auc_score: ^channel_0_group_\d+_roc_auc_score
        avg_test_channel_1_roc_auc_score: ^channel_1_group_\d+_roc_auc_score
        avg_test_channel_2_roc_auc_score: ^channel_2_group_\d+_roc_auc_score
        avg_test_channel_3_roc_auc_score: ^channel_3_group_\d+_roc_auc_score


    groups: 
      avg_calib_roc_auc_score: ['avg_test_control_group_roc_auc_score' , 'avg_test_target_group_roc_auc_score']
      
      avg_test_roc_auc_score: ['avg_test_control_group_roc_auc_score' , 'avg_test_target_group_roc_auc_score'] 